workflows:
  ios-capacitor-workflow:
    name: iOS REINChat IPA Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build Web Application
        script: |
          npm run build
      - name: Sync Capacitor iOS Project
        script: |
          npx cap sync ios
      - name: Build iOS Xcode App and Export IPA Package
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release -derivedDataPath build -archivePath build/App.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          rm -rf build/Payload build/REINChat.ipa
          mkdir -p build/Payload
          cp -R build/App.xcarchive/Products/Applications/App.app build/Payload/
          cd build
          zip -qr REINChat.ipa Payload
          cp REINChat.ipa $CM_BUILD_DIR/REINChat.ipa
    artifacts:
      - "*.ipa"
      - ios/App/build/*.ipa
